### ISSUE TITLE
Uncaught RuntimeError: wrapped C/C++ object of type QProgressBar has been deleted


### ISSUE THREAD

**Issue by gmusumeci** [KIOS-Research/ImportEpanetInpFiles#6]
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:/Users/utente/.qgis2/python/plugins\ImportEpanetInpFiles\main.py", line 32, in run
    s = epa2gis(filePath)
  File "C:/Users/utente/.qgis2/python/plugins\ImportEpanetInpFiles\Epa2GIS.py", line 136, in epa2gis
    pb.setValue(17)
RuntimeError: wrapped C/C++ object of type QProgressBar has been deleted

```
ImportEpanetInpFiles 0.3, QGIS 2.18.3 on Windows 8

**Comment by tveinot** [comment]
Same issue QGIS 2.18.11 EPA SWMM inp file 5.0.0.22
